### ISSUE TITLE
0.0.9 linux build is broken

### ISSUE THREAD

**Issue by vRobM** [anacrolix/cove#9]
Where did all the options go?
```
# ./cove -h
Usage:
  cove [OPTIONS...]
Options:
  -indexDhtLocally   (bool)   Default: true
  -ipv6              (bool)   
# ./cove -httpAddr=:8080
tagflag: error parsing args: parsing flag "httpAddr=:8080": unknown flag: "httpAddr"
```

**Comment by anacrolix** [comment]
Was this the only flag you depended on? A lot of the flags were not relevant to cove operation. httpAddr will be restored in the next version.

**Comment by vRobM** [comment]
No, the indexer and tracker parameters were also used. 

What is the logic behind removing so many useful options?

**Comment by anacrolix** [comment]
See v0.0.10. The tracker flag would not have functioned as you expected. I can consider exposing a tracker flag for the torrent client in the future if you want to open an issue for that.

**Comment by vRobM** [comment]
```
./cove -httpAddr=:8080
[2023-09-11 03:33:21 +0000 NIL] starting http server at :8080 [cove main.go:305]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x140e0ea]

goroutine 1 [running, locked to thread]:
github.com/godbus/dbus/v5.(*Conn).export(0xc000832a90?, 0xc000832a60?, {0x19b1ea1?, 0x6?}, {0x19bf396?, 0x200000003?}, 0xa0?)
        /Users/anacrolix/go/pkg/mod/github.com/godbus/dbus/v5@v5.0.4/export.go:361 +0x2a
github.com/godbus/dbus/v5.(*Conn).exportMethodTable(0x172f1a0?, 0xc000832cb8?, {0x19b1ea1?, 0x13?}, {0x19bf396?, 0x1a?}, 0x68?)
        /Users/anacrolix/go/pkg/mod/github.com/godbus/dbus/v5@v5.0.4/export.go:345 +0x11b
github.com/godbus/dbus/v5.(*Conn).ExportSubtreeMethodTable(...)
        /Users/anacrolix/go/pkg/mod/github.com/godbus/dbus/v5@v5.0.4/export.go:324
fyne.io/systray/internal/generated/notifier.ExportStatusNotifierItem(0x0?, {0x19b1ea1, 0x13}, {0x1f11ad0?, 0x3b9aea0})
        /Users/anacrolix/go/pkg/mod/fyne.io/systray@v1.10.0/internal/generated/notifier/status_notifier_item.go:192 +0x34b
fyne.io/systray.nativeStart()
        /Users/anacrolix/go/pkg/mod/fyne.io/systray@v1.10.0/systray_unix.go:167 +0x59
fyne.io/systray.nativeLoop()
        /Users/anacrolix/go/pkg/mod/fyne.io/systray@v1.10.0/systray_unix.go:149 +0x13
fyne.io/systray.Run(0x19?, 0x20?)
        /Users/anacrolix/go/pkg/mod/fyne.io/systray@v1.10.0/systray.go:74 +0x18
cove.runSystray({{0x1, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0}, {0x3}, {0x0, ...}, ...}}, ...)
        /Users/anacrolix/ags/cove-private/cmd/main_else.go:20 +0xc5
cove.MainErr({0x1f117b8, 0xc00062e640})
        /Users/anacrolix/ags/cove-private/cmd/main.go:323 +0x1825
github.com/anacrolix/gostdapp.RunContext(0x1d33088)
        /Users/anacrolix/go/pkg/mod/github.com/anacrolix/gostdapp@v0.0.0-20230829103518-b45ef8f5e83c/app.go:24 +0xfd
main.main()
        /Users/anacrolix/ags/cove-private/cmd/cove/main_else.go:12 +0x1a
```

**Comment by vRobM** [comment]
CLI only here
